#Magician
for count in range(1):
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 160,  0,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 0, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  (-35),  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  (-35),  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  (-35),  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 180,  (-35),  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 180,  (-35),  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 180,  (-35),  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  0,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  0,  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  0,  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 215,  35,  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 180,  0,  20, current_pose[3], 1)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 1, current_pose[0], current_pose[1], current_pose[2], 0, 1)
  dType.SetEndEffectorGripperEx(api, 1, 1)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 180,  0,  (-15), current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
  current_pose = dType.GetPose(api)
  dType.SetPTPCmdEx(api, 2, 180,  0,  20, current_pose[3], 1)
  dType.SetEndEffectorGripperEx(api, 1, 0)
  dType.dSleep(2000)
